services:
  web:
    build: ./backend
    image: komolafe/mymemorabelia-backend:latest
    ports:
      - "8000:8000"
    container_name: web
    environment:
      - RUN_MIGRATIONS=true
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    image: komolafe/mymemorabelia-backend:latest
    container_name: celery_worker
    command: celery -A mymemorabelia worker --loglevel=info --concurrency=1 --max-memory-per-child=10000
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  celery_beat:
    image: komolafe/mymemorabelia-backend:latest
    container_name: celery_beat
    command: celery -A mymemorabelia beat --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  db:
    image: postgres:16
    env_file:
      - ./backend/.env

    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_buffers=64MB -c max_connections=20

volumes:
  postgres_data:
